### ISSUE TITLE
Write code to be able to run auto paths

### ISSUE THREAD

**Issue by MrTinker64** [SFUnity/Mayhem-2024-Offseason#19]

**Comment by MrTinker64** [comment]
Copy from Quake

**Comment by kyle1455677** [comment]
this has very helpful info: https://github.com/Mechanical-Advantage/AdvantageKit/blob/1a0af700b4b7314103c1dfc515908be3a7fb60c5/example_projects/diff_drive/src/main/java/frc/robot/subsystems/drive/Drive.java
